Update workflow

diff --git a/.github/workflows/deploy-gh-pages.yml b/.github/workflows/deploy-gh-pages.yml
--- a/.github/workflows/deploy-gh-pages.yml
+++ b/.github/workflows/deploy-gh-pages.yml
@@ -1,7 +1,9 @@
+# Push distributable files to gh-pages branch
 name: Deploy to GitHub Pages
 
 env:
   WORKING_DIR: portfolio
+  NODE_VERSION: 14
 
 on:
   workflow_run:
@@ -15,8 +17,44 @@ on:
     #   - ${{ env.WORKING_DIR }}/**
 
 jobs:
-  deploy:  
-    runs-on: ${{ matrix.os }}
+  build:
+    runs-on: ubuntu-latest
+
+    defaults:
+      run:
+        working-directory: ${{ env.WORKING_DIR }}
+
+    steps:
+      - name: Checkout 🛎
+        uses: actions/checkout@v2
+
+      - name: Make fail if the previous workflow was failed
+        if: ${{ github.event.workflow_run.conclusion != 'success' }}
+        run: |
+          echo '::error::Previous workflow was failed'
+          exit 1
+
+      - name: Setup node env 🏗
+        uses: actions/setup-node@v2.1.2
+        with:
+          node-version: ${{ env.NODE_VERSION }}
+
+      - name: Build and generate static project 🛠
+        run: |
+          npm install
+          npm run build
+          npm run generate
+
+      - name: Upload artifact 📦
+        uses: actions/upload-artifact@v2
+        with:
+          name: dist-files
+          path: ${{ env.WORKING_DIR }}/dist
+
+  deploy:
+    needs: build
+
+    runs-on: ubuntu-latest
 
     defaults:
       run:
@@ -31,10 +69,10 @@ jobs:
       - name: Checkout 🛎
         uses: actions/checkout@v2
 
-      - name: Make fail if the previous workflow was failed
-        if: ${{ github.event.workflow_run.conclusion != 'success' }}
-        run: |
-          echo '::error::Previous workflow was failed'
-          exit 1
+      - name: Download artifact 📦
+        uses: actions/download-artifact@v2
+        with:
+          name: dist-files
 
-      # Push distributable files to gh-pages branch
+      - name: Show for debug
+        run: ls -R
